const r = commonColor();
const g = commonColor();
const b = commonColor();

/**
 * Returns a Random Number between 0 and 255 for color value
 * @returns {Number}
 */
function commonColor() {
  return Math.floor(Math.random() * 255);
}

/**
 * Returns the RGB value that was generated by the commonColor method and predeclared in r,g,b variables.
 * @returns {String}
 */
function getTextColor() {
  return `rgb(${r}, ${g}, ${b})`;
}

/**
 * Returns the contrasting RGB value against the predefined r,g,b values by subtracting them from 255.
 * @returns {String}
 */
function getBackgroundColor() {
  return `rgb(${255 - r}, ${255 - g}, ${255 - b})`;
}

/**
 * Generate Iniitals for a person using their name
 * @param {String} text Name of a Person
 * @returns {String} Initials in Uppercase
 */
function generateInitials(text) {
  let newText = text;
console.log("TEST1");
  if (newText.length == 2) return newText.toUpperCase();

  newText = newText.split(" ");
  if (newText.length > 1) newText = newText[0][0] + newText[1][0];
  else newText = newText[0].substr(0, 2);

  return newText.toUpperCase();
}

module.exports = {
  getBackgroundColor,
  getTextColor,
  generateInitials,
};
